Revert "Allow more BuildKit frontend image names"
This reverts commit 702ecfbc64c4afadc8517fe8ea46fe0beb0d3e9d.

Reason for revert: 

Unfortunately the Groovy ends up breaking builds with:

expected to call org.wikimedia.integration.PipelineRunner.<init>
but wound up catching org.wikimedia.integration.Utility.parseImageRef;

See: https://jenkins.io/redirect/pipeline-cps-method-mismatches/

 hudson.remoting.ProxyException: CpsCallableInvocation{
   methodName=parseImageRef,
   call=com.cloudbees.groovy.cps.impl.CpsFunction@13b47af5,
   receiver=class org.wikimedia.integration.Utility,
   arguments=[docker-registry.wikimedia.org/wikimedia/blubber-buildkit:v0.11.1]
 }

Bug: T331497
Change-Id: I79a7b953ed76cbca894931b5f99ff98e10bfce08